# Run Command
#  docker-compose -f jtsp.yml up -d
#  docker-compose -f jtsp.yml logs
#  docker-compose -f jtsp.yml restart
#
#Analyse a project with mvn:
# mvn sonar:sonar \
#  -Dsonar.host.url=http://$(boot2docker ip):9000

version: '3'

services:
  jenkins:
    image: jenkins:2.168
    ports:
     - "8080:8080"
     - "50000:50000"
    networks:
       - sonarnet
  tomcat:
    image: tomcat8-4-jenkins
    ports:
     - "9090:8080"
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
